apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:RgJGr8pw7IMbOyMujhW1ex9V6vMeKFdsAKDR6MJh19tAImpe1XcQIGUqt+hWzlvyIb49L1KvWdodv4uWoWuC3cBZVBkywYoAxlg0NyzO/ONqrFWIw/KHArW7wnoyQ72iHbCc4WsqG9I5Y9siaeB+bu//bpfgyxkX5a7HcmtczB9VjVCZvkP07qN0+WmaOMmvFX7xnwnSdCc/4cJ/y6UZqNwDFFnTKznvOVCLGngQvshreZOwBfcCMG/UnSzCcJeyCjbsYpPLWeOYY94CxHwM1FSi/GYSUxd6YxHafhu06QVavphJj6HC8F/CDdw=,iv:SyFigM1zVslk3rvHkmAhm5XxYeJg/licYIYZRLuAKAg=,tag:GtPNBI1CT1M14dtR92k/fw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpd0VmK1B1UDVoL1ZVb0d2
            VG9kREVKWUJIdmJhM3M2MUsyc2M5VmFFTkI4ClZGNzQ4Mm9adE51Zmo5S2k3bjNY
            V0ZncE45SU5aUHZBSU1iVDl5NUlmTlEKLS0tIFFUM1FDcVJsYzhnV3IrK3diZGE4
            ZGg4TnRraFFEcjdwYzFvVCtSa0cyWHcK85b3ZKd/odLGS+se4VFKAWLdHdwOP8KF
            xPovcnUxVSjfXreFPe+s0TjiYXx0i18ig85EbI+7OEjABZ0iY3SpgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z2y8zzazcrjlmt5t6m2632ke4tjn64gnf0p4xzcuzl97gdktsdfsxsfvzc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T20:39:32Z"
    mac: ENC[AES256_GCM,data:Y16F0lIrxLyTprkupU6daATXCZEtq6egFEBEXds2c7BjDxXuyRMGeS+PKSm9in1vMYZC46BqyLv0RQnbNa00i27E0G2L9Wqist2bzKmU4mH1x/qEKaw9rPv62jxDLAuvkNbdngxY2FfyiSU6yP83tHaJ2+dmYVwtjISnXcL+iM4=,iv:yGGN/HiNiSrY+8R9Jq7jkjlgoAzv7GSC9CcAWYzuRoU=,tag:6BbbXs5iaXyxGUlETH+yJQ==,type:str]
    version: 3.13.2
