apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:dPfzIQdHjp2oeO1Er8D69RaizNfAZX1YP106Ta8GVfaEDTrOQTEMvKy7l2/lddPjhzDcrYu0TyA9eLP96s5YBXoOrp15T6fNV5v/F6dmzTQE8YANrCszwKUDO6CHj1+ZuLWM0yoTPT+21HkdMyfF7XA0LnOaMy/0L396DpH83lzGQVXJCkdCPFYu38nvOOHb7CMpuUjHgsA1E3UJ8e9N2o/v4W4XaHpTewXE3luLKry4PN731bdoHNCiBtyT25HeGGX06BGctw35L5x6YHF348pnsr0nPy/hxRLAeI/sFu720/xuf7YHUA6VVRs=,iv:yVieCCud32483stHGCnpcFcGo8Hwds/f0O/8u7nE0Xk=,tag:X1ln1dKf4rAvAVdMsJ1Uig==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFg4bEdUQ0FX
            N2pRQ0hTVExnMjFuWU1oR0VoNVh6RldyS0UrcW1OdktLcmJVOXRaTUtVamhVQlZm
            aXpGaGtNSmJqUmVTNDNqSEYwU3pPS2g2a3pFbWp0Rm0yOTRGT3NNQ2F2MVFCNmNa
            cm4vRXRhS2NwVEhycVlxcFZIdDZ6WHgrUnJWSE42ZGE2VGx1UWlLMmMyRGhqYVkr
            T0FXREVvSU04YUgzSjJWaWNidk81d3ZpVWpFV0dYYkZaL2hYaEZ0ZEs2bFdYMlBH
            VExOWE1CWFlFcVJWUXcyNkVzZzVFVG9iWVRDa1MrNjk4bS9iWjBzTlRwU2NTNm1T
            VHBsd1RqU1M1L3pwQk9XMEZhaDZFQkxEZjJaRmFzaisrbDVLR3hqL3Z2MXh3YWxD
            bkhZcEZEdUw2bEJONGJ4eCtCUUoxM0RiOE02VEp1N252QjBSWmorekJDV2xXclNk
            U3VlQVFzVUc4c0VlTmpyTDk4ZWxTbXdZMEp6d0FBTkl4S3NMbEZXV2t1b2kxN1N4
            c3BMMUpsVERrV09ydVlVdG5weEVZVlZxK1pqM2FtU21vVTRCT1B6cXRrWG5oK1Rj
            UjJqTUh1UkFQbnYxeHhKMSt2Nk9ST1l4WlRrZE16RHhHU3NiN2VmOVU4ZC92TDIw
            ZXFVUUVBY2V2VGlsSDNqZkZCTXdneFV5aVdyeHhLT0MvcU9JbDZQSEppbjYyUjlO
            SFFoR0RYS2RzV1ByZWV0UlBlZVYvWk9TamhYRm1SUzVCR0VhVW41NCtqSVI3Wks1
            U0tiR3dWSFlJS0VBTG84bGEycUpXeXRnK3htOTN2eTUxekwwdFFsM2Q0OE1VQld5
            UUNucWs3Tm4wVFNFcXdxM1RoellSUVJzZnpDVDZzNkVWcWhueDBVbEZRdW92Z0wr
            aEFhT0VaYUJVRlVNSnZWS0JjcVQ1MWdvR2VhNy81dThHQ0NSbk9rOHEwUk9SbTR3
            WlhDUnc3MzQ3QVZnRi96QVZxcTFvWlZMWGVHendDQlFSUWc3T2JSMlBEMHRwZDR5
            YVpCVC8wdG5pd3F4NC9pUkJyQU1PaEFFR05UajdaMm51dWVHallUdStjVDcrckho
            RGgwc0NaemZLenoxNUlZdjI1dC95M2pST011NmZkRXRrK2JpaHF6MHIzWEJoREt1
            ai96S2NaaDNRY0UrcTRGK0VBc2l4L04rZDA0ZS9nSkVjeEk3Nk1qMFB4cGtTWmRO
            TkhYd1RJZnhJOXhXbHhIQmlON2VBR24zcnBWYWdUeUtsUFRZMFdFMW5icVlNNkhO
            TjF6T0pSZHJqME5DYURGdGpKSW1Qc3dwOXdwK1pjOVYwREtMaU9rNHB2Vk5OMEdz
            RTJFTVdJOXJ6ZlAyUy9FYnpiOG51L1pabzJFWWRnd290MnhEZWJxK0N1Tk9kemhz
            T092dFptTlE1eXhYQ0wvZG8zNXNCSkwwcjRsRHZaeVhlV05QUHh5NW16d0ZTZXlu
            U3YzK2pxZHBqQ1ZWQzU2MzNGQ1VyR3hzUnF1WUJEejVIbE1lZWdHcHQxcFU1YzhX
            dFZ4MlRwampSUkR4aG5nWDR6UkQyTXk4V3lHOTBFVTVRalhhT0VqQStNcldlZ1pH
            Sm1HUVB0QlZqSmdEcVBFYm9LNGpxTmlHRDJDQzgvOVZCUkZqZnJZMm4vdmFzVGRJ
            a1pjdk5oMk1oRkxSbE1rWmNXSzhRL2xFUTdnNnZXUFhaaW1qMTB1dXgzUFFlSU1O
            UWNpUnRySXRCRHRtbC9CdnlUOWJFS1BVOU52Ums4Q21GYU45MTU3SjdwcTJLL1FO
            NGExdENVcm5VYUZLRElQdlc1ZGpZRGE1QzlieS9OakE5cFZVNGlkQ3E2MEp6UkFS
            UFo5NHprR091U25Oa2xDbmpqcU1WRkRPNzVuT2tyQ3FrVkRDVWw3VHl2RzNKbTVC
            WFUwZ0gyU0NCS25rZUxjMGE2clMxcWdEWFpucTU1YVgzZnBSVEk5ejZQNFVmZwp4
            ZUZvdnc5NnUxWUNLWGJBREthZ0VmRXplaGxtekQxNHFMQ3ZERWJ3RGE4Ci0tLSBy
            YW9UdmViRE1lZzhra1gyb1dMOEc4ZkxhSFJqOGJabHV1QmNVMklneEFVCjL2CdEw
            wYcfnnE1G8yCYQtpbq4hqkeBZ4M1akw72kSZ4ooxi3J4dKj5DSgd2jyvsbyEJj/5
            HTcfZ6TV0UYZk0M=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq16yps4efc86kg282my9x04f34lpqmhx8tqhyy42rklzan3q7v0j6pzsfhqpynxhwv66tdfkjh24njmde50n2j3fmtxgcan39ky2ykewuuh0vfxuh5c2nhkp9lnadmmtff5khjzhzfysz7wxzyae58jlz305ywc4dp3xp94a43y8rc9f2z2s24nsk6xksur56lrlxrfur52f4k8s5m4j076q9jd07yqvrz2c409pup509q29y8rqe68llttqj8grr0542kl3mxs7ygu0l5rarzc4qxxcell66cscpthzpy3wz2zulkhf3zup9ke4ty5ljsjez8rxwsc2r3yuu8lku43ych2scsk4zsg4p9zaupj536z0yvcqh9yy4ksuzfsvsqmf42hcwjxpc3pvtl72r5c9mas0qnfvuv88fev58f5rzg0yenarsjdarpy922gjhrq0qe6vtamxv54sx290pfkkq8qsfpq3gdf45uyfeqxhtwkj4u56yg0gv0l05ranpyq9kmkdxcgpz98qxfdc5jw5nmtp4v4jkumgad6uu27xnmsgt5eatntxhy6s7743mgzu62z4cp98w3vawd2ynzlrzedu6qe8uu943vc9pe7732u99me27rfge3v7g3qh5a8vkfsc44tpqsc6d4fyvpg0ls6nz4aequszg2w77m94055r8qezc6hpn7q9kxxfck0tvh9zaugdvma3emxgkyg7y8n6mhjarm6d2al46ymr3pvjnjpe96hth5kae75ugvp942wpxkz7vkpn060scyufrr05mj7tczzm474ndpsacegznswhfyu6sk8e7vzvc42c8xds6t5vqex0vhh4t0ercp7ye2wjt65ym5lpm5q3azx3jzxsq7xgrxxynxcx08s5edjefad3gat6u4cnxyv846dp99qu0xnshlxqpj3dvnmu3mpzwfs490rg6lx4rmky7xm3xj4rv63v0ejk3wda2kmqafukd62vgcyvt6rv57a8xw276qcldjchluhgwem3ns0suhj63v2lrss9g8q0fthdcl0spfnungwv98352xnr5f298r8zauj9vf63n3tu2y2y83q2aaxmzw3adply2x5tkuql82zq2qplzgefmgg3nyp0yv9rrarwqqcua808u94mmj37n89xp4qnqwyeq2x5f6zfdpe3zd8g7a543gease2t5xxvwk0v4nv0086uanrevm6yjmr9crplzcguk78qw90xm4pmkx76yxcqzkkz4g4pn5djg2lv3p36djds825pugfq5yxrzgu09sl0a328v3hygnugd9mcnrnqpumwfvh2kzyh3lg08qaq6ggcamjdnzn2dswjznxhpfz3gcs6ynxsv3h5jj38dhaz4d62gyvppxgsc6nl9nv0lzcus2hnp3hlzmzdt5fn9qxz728gj5m5nvnp78zgff2at58je52v39q99cypcg4d9nv2nzfzmqxrr4wvwwxjn3nfyjclxzkqad03wlm2d7qzmtq8j9qrvknx4rjeyftv6my0eqd67mwkmhkt7gzgk0pqax5mfu6xl6z4aqzjftv56g0ewfuh26vyj49zwusjm39pv70cqr2de5yn4g4mud98m4kg4r7fswpwyzz5h5xq6cwglfvfp7ped8wfrffk4p5sanpw5lpp5l5dejf4exclqcczh09nz5nf7hg93f4vc57hjenl4qc3fda23a0acgu8kyanqyh32fvckavvdfk92mcpfesetkpj8m5aywaqu4upujpgzjmdn55ynrvpm0w3k7n6sfwx5k7mr8w2kd5uexs37zdkjjz598kp4zg8870zal9d0x9tkh6kf54g83rqwc6ejssyt3ukn42gqd8u8d3uhsl09gvqgp8w75x6h7z3pqk8awlh8qfcs989lu3k395gd64jl6um74h9ajd9hhfukdjgj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T11:57:32Z"
    mac: ENC[AES256_GCM,data:k1KQ47AX7Ft7L4R+esOD8sec/fFTpEyZwOjKcr5qFG3fcZxrjKXq47ccjyZ9ERHCmiqHTX5LLh6zHxSe4GfItxEn2F1ezhJbHw5UjCIQ8BzhE+fc9gv8rJ9mZPKNKT8Gw5mL357xcMvaUL5uWk+l5Ce8W5xQCcCJlGlJPRoOAvU=,iv:cdxLdA8umua7I18XeO7MlSOHmIuNZtfZUbXKS0wh+AM=,tag:rnDsf0K+5rBU869vOnA+mA==,type:str]
    version: 3.13.2
