apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:QTwE+3hDHh1QoQkFTFgbmVpSvpTg4ogm9mI01vu+qwzWKKkh2GU7zrqblhbQyvEmlYbvSGYJA1E5ATM4muPohun64wgP+NHEIbbMcZivhEhvG+5l/pbKrhmAr0UXA02Qi+WJda3iv+pba1dMwsEO0koroMwZbtBMcBBuhcu0oLWJ8GLqlSr9KuXKVXNTbN3DqaowDooVJtutIsDKC/EAQUvWSUz/yNT9N4rEVYPW29vu8dwjrzPLilqxNUzeh0vs9PnIwQTQ/wyGYXc91nfYNvKSCRo8D5DGXMgRQuh5aIr7y2xAYtgs3wUlJ94=,iv:q+C2G8P8U7MIZ3fuBwpFTlUy53iaH5zE2TPqoKXdWZw=,tag:8o/uAY+dTGWQebAfTKP5Yg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONHpPTno3dnlLV0VoMkh2
            UlkxUEVQUWFHOEZKbGVydnBLZzlzaFV5NXpnCnVuY0dNWkpNZUsrMDQ1QjA4T2Js
            Y1pDdmwra01MZzEzYUF0OVY0dkNPb1UKLS0tIFNxZmxTZnhKTUZGQ0Z1ZW5PTHhX
            NU9BbkRMdzVjZU1qWUhGb0RwQi9zTlUKlIapyqLr95xbC3GqGr7/qktRCqgv9I4/
            4HI2yRQfU3GdqX6W4gqQ9NNnZQY5XsJx02I/4bhM1lnInvJW29vJwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z2y8zzazcrjlmt5t6m2632ke4tjn64gnf0p4xzcuzl97gdktsdfsxsfvzc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T06:43:17Z"
    mac: ENC[AES256_GCM,data:6NlXH8StRb7CefDwdmeT2IwVwRZPWA1DQjWwNMsNKQ5EOa08Tj53iv6PnTV8GYoiEu2caDJfWAC/e6bv0RYVJ1onqimEZ2C4COAUpnz1aMjrEbV+LajVdLXOG6dFfKOXbFR09bgiCDsiIbyXmowN2DJ7SFwgg92YazQhnN6H8xY=,iv:VBsLxxCRCdAx1weVSoF/Ym/qXp0Lu0tfUHpx4bF07X8=,tag:yhdHR/8MubkT87Yti29eag==,type:str]
    version: 3.13.1
