apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:grfkbVwYzipEumXu,iv:d92JEZfPQJ8jebWEgcrq6YZFIlbygpB+iHaEOnQ42rA=,tag:aMzzBk8G8z1DvJElD2yxNw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:u+9xZ4ZwqsZ1u40TJP2izTAZYSx6gUn43WGIDq97Hg3La00ZNxtFIbLws2A=,iv:DcRi18maVNSa8e0ovuycvwbIn4P+/68VdYYa2spVjNY=,tag:5+BbXp+8h8YGMFUBAYX0Ug==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQW1ja0YwUVpuWmwwOTVS
            U1RvMExVbDZzdzZQdlRKRmMxejRscmtBQkhjCmhjTzI1cXBNTlVxSjJtY3doWXFa
            SlQ4RkZaWW4rTGVPNXpleXRlcHl4bVkKLS0tIDB1dWh3a0JSeklodkt2dXJCNW5m
            bTdJTnRDMmFsbzM3TXVKV0tqUytxWHMKrYMdTuG8TLPIhlsMmMpxJokKqwuy+krb
            Mx1inqESH0HXUgzgW90SgHQeBq+s7srLTUYWB+Ubi9yMtEwAioRNVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z2y8zzazcrjlmt5t6m2632ke4tjn64gnf0p4xzcuzl97gdktsdfsxsfvzc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T08:01:06Z"
    mac: ENC[AES256_GCM,data:837jq6Ol8lvWUjlqB6/yKG146VPI3v71BcnIt7tVc+72eiPoAKfvgqZGxYZbtce5tggkay9nHi2Wb+XGxpoGVWEA/mha+awfxLelC1TxY0gY2CYGQ1pA3Y/OR1l4oSSqvLsfqqXIOFxM+E99uVdB/MUqEVa9MmYrqP1/+6GgnWI=,iv:4ZTd7wKmTlJ15hw1GF9lpZdnEgRvWri0lte78qronTo=,tag:xipBEx4QQaCgKAJgVNV9Jw==,type:str]
    version: 3.13.1
