apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:LzbyznCJZA5FgqzY,iv:zyHgbYzdrOYLMQnU4zL3i69QzFkHUn4gXutnxis/klQ=,tag:z1O3i+tTt+UH5Y9xwVHTig==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:tXtBR1Fb8litxQ0naxM3EqXNUWUWKkU3T5npJXu0sJQXzg6WD55a+LwsqJ0=,iv:nMaVHCppNLk0iBX80rhlfTnJiZGtvsCKQJ51XHqUPCY=,tag:beiDcsDuB5i4a5vAkHKluA==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEgwSGROTUV3
            S3JhaHZaUXU0eFY3c2Q3NnBlNlZRZkE1bHhVUVI2Y0FSUVZQeTZmb00zcVJHUXAr
            enoybis4TnVRTkdacy9qMTFrbDhKNXpzU2s2VVRzdnNDUlRLYVYzdEMrUG5ZUkU5
            dEg3Qnk5R0U2ODRmM1RMM2VGV2pQOFh4bEFDTXhZbVJMRUZLNGtWRGhseVlCOFlw
            TlA0R05YR2JzbjJJcndYQ09mNHl1THYrSkhkejdOV2JyREVFbE1Fb3BLUCttMEJS
            RkVzU1piYUY0SGpzRVA3Y2MwWjFobVkxRUUydkg1ZkxqTmpZS1N4eVZBSE5ZMWMx
            YkZrZSs5WWtFeHpxSXZWYjFhTTNmbFBZS1VDc3p2ODBJZmVGTlZxZ1lXQ1MwcmJM
            QlRuakMvRGVsOE5FdldWTWpFVzMxckM2V0doRG1CbnRZMkNyNkZFcGcrQ09uV0Nj
            cUxTRStZOEpISHkvQ3BxSFhVS2NYaTVhVjFLS1AwYmViMTduQ1VRaUg0V2h0SEkw
            Vy9kOE5qa2dCWmN2YjhSL0pWQllndmJuRU0vUDIrMm9qRHgvZWxjUmlYT2RJQnAy
            TzFCaTAvWGU3OXk4MlFwNTRyeE5wa25xTW0yTmNiaUdONHFJSy8ycGZoMHVxWEs0
            V3RBZ0pSaTNwcVN2OVlreGdlN3pxUG42cE5iYSt3TjRKdy9WTXVDbUNzaUFtK2pp
            OEtYNXRtL0cydTN0Y2xXSTRVMGlhQ3lld1E3Um5IN0hiSUdDc1F4ZWVESWZDMStW
            T3ZvTUQ1ZzdnelljbCs1dGpZR1piMVdrc1RuS2RSQmVpYVgzM0lFcysrdkFXUGh2
            b1pRNHVudlhzRHVhVkVyQnRwbWRuVVdPWVY4Qm4wYVNGckxCK3lDd1F3citPQ09j
            K043d21GVnYwRlRSZlRoRXBVTllZa2VwUXM0cnhpV2xHbTJvM0ZjblVKYmNrUE5X
            aTNQRHYwSFlIU3hId3dMSkZIbnY3TzNCZXFxdnNzSDlYNHJlRmdBK05ablRnVngy
            bU5Vd1ptY0VRQVBXU3QvdW9kdGI4VVUwZUxKOE5acGZ3M2hPeE0xNHVwbzFiRGd0
            c0d5RTlhY0JocWIza3htVFdyVXZadkI0UEpQbUF2U1E1c1Qvd0sxdEF6ZEJXbGdy
            SHljM201RHdUOGl2SUQ0Q2M5SXVxeU1Ldlh1QkhmR09Mam4wMmd1Mm82Vi9tMDNt
            WFBXWFBTOTBsS2tlQlI4Zml3L0NrbzhLSTFqK28xc0dmcXR6b3BOU3o2cTRQWHlT
            NU1OdlQ3UE9HdXA5bEtIbUpvYXZwZEVqQTdjQk9vM3gzblFsTUhBdlZ0a0pibFVQ
            OG0yYzlqMy9PaDQ3NVZPZGRCRE1IRWp0MWRqTWV4S1hrdS8zRnIwZVlycUc3QXdj
            cHZwemh1SHZpSHptMzVjYWhGa0taTXdJMW9NK25zeldONGp5TStvOStnVFMvS0J4
            RWRXdE90bmpDVTN6cWRsUDlNdWYrTkJ0WEc4Y3ZYRnB0M1hDNUkwTWhsM3g5bXN3
            UEdLbFQzNUczRzZkNlJzZFk4ZWx0alN0RWE1em9VYWNYamFvcjhQUFlhcGlGN2Jz
            UEhYY1k5RFBnRjA5SXloTzR0TzA0RkZSUTdSd3ZFQnZyZ3pmSTZDcEVHNkJWUkQ2
            NFQ4Z2VWMW0rSUpSc3J6eWVsRGxjTFltWEc5ZnE1b1luWXBSZGFpeE1vTlJyNXR5
            eGdHNm9lRTJua0Q2ZXEyUFp4bFZXRTJZSEhvQTRjTHcyZlp3QWs2aUNIZVkxQjVU
            dk1GTDFhRWRtUEEvR0tKeTIvd2FVZC9FdEx1SWRSVnBEaWdkalg2ZDVYTGduaGZr
            aUc4dWlwZnUxQzlMWENGZWJpdjJBdkdKdVdQR1UrWk9sTXdlRjhxMjhDZm5TT2R6
            OXhsU0pWUmpvTUc4NTR2aE5na1A0b20rZzdpZHpvUUZOSUhUNDRIbTUyRVdSZwpX
            K2VEaFN2Uldab3NrVmlVdmZsczFVeUt1UXJKYzJJNjFFVFpSWkdNdldRCi0tLSBU
            bGVpWjEvMDAvYndTTEdFSktCTU5mb2l4c21ETDNlUVhSa2FkR0ZjWnVFCtfZa0rZ
            wjMOUSjKOOKYYadE3My9kzJMPc9kRLly2dT9B97v9Fd1MDi8TOwACaMHjycTcLbb
            be6olllNCRx06bU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq16yps4efc86kg282my9x04f34lpqmhx8tqhyy42rklzan3q7v0j6pzsfhqpynxhwv66tdfkjh24njmde50n2j3fmtxgcan39ky2ykewuuh0vfxuh5c2nhkp9lnadmmtff5khjzhzfysz7wxzyae58jlz305ywc4dp3xp94a43y8rc9f2z2s24nsk6xksur56lrlxrfur52f4k8s5m4j076q9jd07yqvrz2c409pup509q29y8rqe68llttqj8grr0542kl3mxs7ygu0l5rarzc4qxxcell66cscpthzpy3wz2zulkhf3zup9ke4ty5ljsjez8rxwsc2r3yuu8lku43ych2scsk4zsg4p9zaupj536z0yvcqh9yy4ksuzfsvsqmf42hcwjxpc3pvtl72r5c9mas0qnfvuv88fev58f5rzg0yenarsjdarpy922gjhrq0qe6vtamxv54sx290pfkkq8qsfpq3gdf45uyfeqxhtwkj4u56yg0gv0l05ranpyq9kmkdxcgpz98qxfdc5jw5nmtp4v4jkumgad6uu27xnmsgt5eatntxhy6s7743mgzu62z4cp98w3vawd2ynzlrzedu6qe8uu943vc9pe7732u99me27rfge3v7g3qh5a8vkfsc44tpqsc6d4fyvpg0ls6nz4aequszg2w77m94055r8qezc6hpn7q9kxxfck0tvh9zaugdvma3emxgkyg7y8n6mhjarm6d2al46ymr3pvjnjpe96hth5kae75ugvp942wpxkz7vkpn060scyufrr05mj7tczzm474ndpsacegznswhfyu6sk8e7vzvc42c8xds6t5vqex0vhh4t0ercp7ye2wjt65ym5lpm5q3azx3jzxsq7xgrxxynxcx08s5edjefad3gat6u4cnxyv846dp99qu0xnshlxqpj3dvnmu3mpzwfs490rg6lx4rmky7xm3xj4rv63v0ejk3wda2kmqafukd62vgcyvt6rv57a8xw276qcldjchluhgwem3ns0suhj63v2lrss9g8q0fthdcl0spfnungwv98352xnr5f298r8zauj9vf63n3tu2y2y83q2aaxmzw3adply2x5tkuql82zq2qplzgefmgg3nyp0yv9rrarwqqcua808u94mmj37n89xp4qnqwyeq2x5f6zfdpe3zd8g7a543gease2t5xxvwk0v4nv0086uanrevm6yjmr9crplzcguk78qw90xm4pmkx76yxcqzkkz4g4pn5djg2lv3p36djds825pugfq5yxrzgu09sl0a328v3hygnugd9mcnrnqpumwfvh2kzyh3lg08qaq6ggcamjdnzn2dswjznxhpfz3gcs6ynxsv3h5jj38dhaz4d62gyvppxgsc6nl9nv0lzcus2hnp3hlzmzdt5fn9qxz728gj5m5nvnp78zgff2at58je52v39q99cypcg4d9nv2nzfzmqxrr4wvwwxjn3nfyjclxzkqad03wlm2d7qzmtq8j9qrvknx4rjeyftv6my0eqd67mwkmhkt7gzgk0pqax5mfu6xl6z4aqzjftv56g0ewfuh26vyj49zwusjm39pv70cqr2de5yn4g4mud98m4kg4r7fswpwyzz5h5xq6cwglfvfp7ped8wfrffk4p5sanpw5lpp5l5dejf4exclqcczh09nz5nf7hg93f4vc57hjenl4qc3fda23a0acgu8kyanqyh32fvckavvdfk92mcpfesetkpj8m5aywaqu4upujpgzjmdn55ynrvpm0w3k7n6sfwx5k7mr8w2kd5uexs37zdkjjz598kp4zg8870zal9d0x9tkh6kf54g83rqwc6ejssyt3ukn42gqd8u8d3uhsl09gvqgp8w75x6h7z3pqk8awlh8qfcs989lu3k395gd64jl6um74h9ajd9hhfukdjgj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T11:57:38Z"
    mac: ENC[AES256_GCM,data:pMv8JuHVYLAWZWgH7zodwZSHObXrvga5zrFLDv4H7AmrQyStbF4stk/yUUfwltUEmkM+Z2igGOe0YbV4lxx/jp2IZF2qMNZdr0Fm5fFICGpdSwD+fS4GDFEEiAu7qYrJN/E3NbWS+jgdJw/NH1SoMHyuhxLRVOXfc8rgIKGZhvw=,iv:cml0QNSgKB2N1vlsVxRdlIgZySN5B7nSJZoUHLyENfI=,tag:F0RwFVe8akrOtim6sduFiA==,type:str]
    version: 3.13.2
