apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:D3HUJUo1x60o+ILJWHthRdyPLopMm58l6K9R6TPJNOJOsxNZ1Cg3QGvq4DYil8wXp76b9BDMy3E=,iv:cfqmmENiJfCzdJstJ58H+dKejUdur93zOJ1xkKLXEsQ=,tag:PUGitrHpPQPdbP/GVb8Eqg==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGFCQUNFa01Y
            RGpJMVp1V0ZPN0d3VHpQWUxjRWhKV09RbHltbkEvS2RrYTB0UWtVcC9hTWgwRVU5
            a3JpVnZ1ZW5vdURQOU44V2ZWNUtRYld1WGJuQ0cwbnEzUVF1TnE0R0d5dTdDQllJ
            NDZOTGZPWDJvMWIxdm5pRFhsZG9TbUp5MTBONVBxbnlaZnFucCt4cnBQVWxxYm1u
            NzlVcXdsbnh5RUhUYmh1YmhWQkI1ZTBKL2hlUHRYTFVIWUM4bkZ6VnZDWU11YzhF
            d24xdVZxanNqTzJCcTIzdFZNWWFaQTNJVHhpeDdvb1l6Q3Fkckd1ZGRncFlOdkdm
            U3V5bnFvY2lTSVg0WTlqZWp1VXpVc2UzeHpManA3OTkwZXdYeUNJRG55SFdzdi84
            QktFOXYwYnZHWi9HaFcwVXF2a3BGS0Z0Nk1DbG4yM1Nka1RxbU85TlJrWDJjNUN4
            MnpLdGFjWGltQnB2Si9Ka3o4QTlWT2tSd1Q3c09QRUtsdlRMZUUxSjB1bjZFRGZZ
            RmNDZVF4cEtqRC9veHpxTGJRSjNoanVkTFkyT3V2WlBiOEphb0FxUk9HcTdjVXRk
            NmwyeEJJNVJpWUc3ZE9XcmFwMEYzTjFlSHJCdWtDa3dSQWRTa0R5MGVwd24zM21Z
            UUwzQzNWVEVMN0phMFVCaVlFZ0tXVDh4WFNyckVSZGIyWHdXdDFscUptR2FQQlp3
            OGJ5YXI1RzBPalFyMTNUUXVRcXRTWjNNUU9BQlYzb292WTFUTUhvN2ZiRG5kdUdj
            b2xwV3Nic1FvSXk3RFI5aTg1STRYNm1GY1dEYTBqWUVoM3Nnb2x5cXVyWkNtQS93
            RThaRHRpNWJHbjQ4NkxmeEJZbDhoY1lKam9hMTVnd2ZDdkZHQndCekp0MXNjbXBz
            YzVSOFVrUmNYRTJ4SXhEbXF3M2Nsak1RdWhtYWMwd2hienpVRUJUZUFqTU5RaDZT
            OVVxVGxJTmgzZlhkNU5mMWxvcjJlVld0RjlQNlc1M2JORHFOcGhpTFk2T2dxcWdi
            OXBLSDlzQ0xYanNyQXdxdVNEaXVXRndHR3p0MWxndEhOVXBtT0ZDaVZaZXFra2lW
            RnE3ZzJGbFZjdTVqcjJEc091RnhLVmFmOFN5eHE1czlXMjE2YU1XMEl6dDZhRms1
            VFFKM1VHM1JKWFROOUhkcXhZRmsyem5GUUYvcStBMFNoTUpRUjRVOW42blRqb1RT
            U2wvdFFWcTZpSUVoYVpjdGFYZWw5KzJxTCtrVVd5UFZhcXJQSHVha1UrdHFVOC8y
            dXBVVENoUTYyc0pwVjR3UWtoNUhubHVYc0hRTldMSmxTZURYUmtFT2V3enAyMVFr
            M0wvV2RzN2ZZcjJEV2xHVW03d0NPM01sci9MZXA2cWF0VWIya29Na0FobGYrV0tt
            YlNkdDJiOS9rb2ZDTFBtK3dCZTNHYkc5R3hOZlN4cXdsbHV0S3k4czNVeENjeHFW
            NlB3M0ZYWUpVdDhKZmxtVFBvVUhmeGVPdDd4eFp1U2FEbWRrajQxaDZURUd3bjNn
            QWk3eDVBZ3dQdmhoVk1WZHJNSzZ6QnQxekVkd1JPakp4NFdLOEhDRVg3UFZ2RUJH
            RzVXcHFQbTlZNjJKN2M5K01IQkJRQjRvYjFYaHhwemhvdzZzYkNvdDB5RXk1K21Y
            RkpkVTF6SHMxZjc1WlBsdldKbithd2ZpSmVnRDAvajdrYSsxZUJOeEtiT21PdHM0
            bjNRWXlJQkdxcFQvQ0pyck5jeUFOVjR0bkJaYW9rMklUQzc2TG10TmFldzVKSU50
            N0hDOVI4Q2Z6WHZhVndZSVlENFBMbnMwWjlEMHhTcE9MZzNGQ00zYzhDckZXOXVP
            emdkZVVxS1JJa2xCK3dCOWZZNDJQbTdlaEE1M2cyRGhEbmdBWWlLMFgwNEM0OTVs
            aDhPUngxanM1Ui93M0RrZkMwUHRpZEwvak9zUkpXSW1PeG84VTlvdmtoUUpCZwoz
            clFIZktCWCttZGIrNXpTMVhNby9yWE5La2NpaXFjTUpTR09JNTd0T01VCi0tLSAv
            TjZqV0lRMXdiU2ZVcDEwOU5LWi95eEFURXdLMU9LOFRlV0owMmZ1UXljChhG8UBx
            tYfJtXXm418jbICexPZuO0vRGZCYPYofu+dBHhKajFejM0LyZsvPr3OXBJXSMyTD
            kXyJ5xyCJiMzhdw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq16yps4efc86kg282my9x04f34lpqmhx8tqhyy42rklzan3q7v0j6pzsfhqpynxhwv66tdfkjh24njmde50n2j3fmtxgcan39ky2ykewuuh0vfxuh5c2nhkp9lnadmmtff5khjzhzfysz7wxzyae58jlz305ywc4dp3xp94a43y8rc9f2z2s24nsk6xksur56lrlxrfur52f4k8s5m4j076q9jd07yqvrz2c409pup509q29y8rqe68llttqj8grr0542kl3mxs7ygu0l5rarzc4qxxcell66cscpthzpy3wz2zulkhf3zup9ke4ty5ljsjez8rxwsc2r3yuu8lku43ych2scsk4zsg4p9zaupj536z0yvcqh9yy4ksuzfsvsqmf42hcwjxpc3pvtl72r5c9mas0qnfvuv88fev58f5rzg0yenarsjdarpy922gjhrq0qe6vtamxv54sx290pfkkq8qsfpq3gdf45uyfeqxhtwkj4u56yg0gv0l05ranpyq9kmkdxcgpz98qxfdc5jw5nmtp4v4jkumgad6uu27xnmsgt5eatntxhy6s7743mgzu62z4cp98w3vawd2ynzlrzedu6qe8uu943vc9pe7732u99me27rfge3v7g3qh5a8vkfsc44tpqsc6d4fyvpg0ls6nz4aequszg2w77m94055r8qezc6hpn7q9kxxfck0tvh9zaugdvma3emxgkyg7y8n6mhjarm6d2al46ymr3pvjnjpe96hth5kae75ugvp942wpxkz7vkpn060scyufrr05mj7tczzm474ndpsacegznswhfyu6sk8e7vzvc42c8xds6t5vqex0vhh4t0ercp7ye2wjt65ym5lpm5q3azx3jzxsq7xgrxxynxcx08s5edjefad3gat6u4cnxyv846dp99qu0xnshlxqpj3dvnmu3mpzwfs490rg6lx4rmky7xm3xj4rv63v0ejk3wda2kmqafukd62vgcyvt6rv57a8xw276qcldjchluhgwem3ns0suhj63v2lrss9g8q0fthdcl0spfnungwv98352xnr5f298r8zauj9vf63n3tu2y2y83q2aaxmzw3adply2x5tkuql82zq2qplzgefmgg3nyp0yv9rrarwqqcua808u94mmj37n89xp4qnqwyeq2x5f6zfdpe3zd8g7a543gease2t5xxvwk0v4nv0086uanrevm6yjmr9crplzcguk78qw90xm4pmkx76yxcqzkkz4g4pn5djg2lv3p36djds825pugfq5yxrzgu09sl0a328v3hygnugd9mcnrnqpumwfvh2kzyh3lg08qaq6ggcamjdnzn2dswjznxhpfz3gcs6ynxsv3h5jj38dhaz4d62gyvppxgsc6nl9nv0lzcus2hnp3hlzmzdt5fn9qxz728gj5m5nvnp78zgff2at58je52v39q99cypcg4d9nv2nzfzmqxrr4wvwwxjn3nfyjclxzkqad03wlm2d7qzmtq8j9qrvknx4rjeyftv6my0eqd67mwkmhkt7gzgk0pqax5mfu6xl6z4aqzjftv56g0ewfuh26vyj49zwusjm39pv70cqr2de5yn4g4mud98m4kg4r7fswpwyzz5h5xq6cwglfvfp7ped8wfrffk4p5sanpw5lpp5l5dejf4exclqcczh09nz5nf7hg93f4vc57hjenl4qc3fda23a0acgu8kyanqyh32fvckavvdfk92mcpfesetkpj8m5aywaqu4upujpgzjmdn55ynrvpm0w3k7n6sfwx5k7mr8w2kd5uexs37zdkjjz598kp4zg8870zal9d0x9tkh6kf54g83rqwc6ejssyt3ukn42gqd8u8d3uhsl09gvqgp8w75x6h7z3pqk8awlh8qfcs989lu3k395gd64jl6um74h9ajd9hhfukdjgj6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T11:58:14Z"
    mac: ENC[AES256_GCM,data:8lgn6gHrJ2CY9Bj41PJtQZOB8V9lsnai4F/6znFEFmKXWBp2y2mE9Y7TB6/cbP7da1AKyrn6RzCybjyprLjOHXp3eOtw4i9MAxEdkXGSYsnR2maQfvc6x8ZWZFZvMSCT3ZQSpj/T7s5aNUJG6cwxZrseqrrvK50b15O+gbEHGhg=,iv:m9mTgqP/qblhsJ/viSUBjd+PgKiU0/XD/m0vR0Xo4vc=,tag:QM6MA4AYhGyc8gWFqS17+Q==,type:str]
    version: 3.13.2
